# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
          matrix:
            service: [ 'SavingAccount', 'User','TaskService','Auth' ]
            db:
                - saving_account_service
                - customer_service
                - task_service
                - auth_service

    services:
      mysql-saving-account:
        image: mysql:latest
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: saving_account_service
          MYSQL_USER: root
          MYSQL_PASSWORD: ""

      mysql-user:
        image: mysql:latest
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: customer_service
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
          
      mysql-task-service:
        image: mysql:latest
        ports:
          - 3308:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: task_service
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
          
      mysql-auth:
        image: mysql:latest
        ports:
          - 3309:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: auth_service
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Wait for MySQL to be ready
      run: |
        for i in {30..0}; do
          if [ "${{ matrix.service }}" == "SavingAccount" ]; then
            if mysqladmin ping -h "127.0.0.1" --silent; then
              break
            fi
          elif [ "${{ matrix.service }}" == "User" ]; then
            if mysqladmin ping -h "127.0.0.1" -P 3307 --silent; then
              break
            fi
          elif [ "${{ matrix.service }}" == "TaskService" ]; then
            if mysqladmin ping -h "127.0.0.1" -P 3308 --silent; then
              break
            fi
          elif [ "${{ matrix.service }}" == "Auth" ]; then
            if mysqladmin ping -h "127.0.0.1" -P 3309 --silent; then
              break
            fi
          fi
          echo 'Waiting for MySQL to be ready...'
          sleep 1
        done

    - name: Build with Maven
      run: mvn -B package --file ${{ matrix.service }}/pom.xml


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
