name: Deploy Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ['SavingAccount', 'User', 'TaskService', 'Auth']
        db:
          - 'saving_account_service'
          - 'customer_service'
          - 'task_service'
          - 'auth_service'

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: ${{ matrix.db }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and deploy service
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/${{ matrix.db }}
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ''
        run: |
          cd ${{ matrix.service }}
          mvn clean install
          java -jar ${{ matrix.service }}/target/${{ matrix.service }}-0.0.1-SNAPSHOT.jar
